services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    networks:
      - webnet
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/extras:/etc/caddy/extras
      - ./data/caddy/acme:/data/caddy/acme
      - ./data/caddy/certs:/data/caddy/certs
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    command: --config /data/settings.json --address 0.0.0.0
    networks:
      - webnet
    restart: unless-stopped
    volumes:
      - ./data/filebrowser/files:/data/files
      - ./data/filebrowser/settings.json:/data/settings.json
      - ./data/filebrowser/database.db:/data/database.db
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)

networks:
  webnet:
    name: webnet
    driver: bridge