services:
  caddy:
    container_name: caddy
    build:
      dockerfile: ./caddy.Dockerfile
    networks:
      - homelab
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - path: .env
        required: true
    volumes:
      - caddy:/data/
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/extras:/etc/caddy/extras
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    command: --config /config/settings.json --address 0.0.0.0
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data:/data
      - filebrowser:/config
      - ./config/filebrowser/settings.json:/config/settings.json
    restart: unless-stopped
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data/notes:/space
    restart: unless-stopped
  polaris:
    image: registry.gitlab.com/connectical/container/polaris
    container_name: polaris
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data/music:/music:ro
      - polaris:/var/lib/polaris
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - homelab
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data/movies:/media:ro
      - jellyfin:/config
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - homelab
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    env_file:
      - path: .env
        required: true
    volumes:
      - qbittorrent:/config
      - ./data/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

volumes:
  caddy:
  polaris:
  jellyfin:
  qbittorrent:
  filebrowser:

networks:
  homelab:
    name: homelab
    driver: bridge