services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    networks:
      - homelab
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy:/data/
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/extras:/etc/caddy/extras
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    command: --config /data/settings.json --address 0.0.0.0
    networks:
      - homelab
    restart: unless-stopped
    volumes:
      - ./data/files:/data/files
      - ./data/filebrowser/settings.json:/data/settings.json
      - ./data/filebrowser/database.db:/data/database.db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet
    networks:
      - homelab
    restart: unless-stopped
    environment:
      SB_URL_PREFIX: "/notes"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - ./data/silverbullet:/space

volumes:
  caddy:

networks:
  homelab:
    name: homelab
    driver: bridge